### ISSUE TITLE
Class "Rector\Composer\ValueObject\PackageAndVersion" not found

### ISSUE THREAD

**Issue by jtojnar** [efabrica-team/rector-nette#96]
https://github.com/rectorphp/rector-src/pull/2865 removed `PackageAndVersion` breaking `NETTE_30` setlist.

**Comment by lulco** [comment]
@jtojnar do you use it (composer changes) or it is just problem with removed classes?

**Comment by jtojnar** [comment]
Did not mean to use it specifically, so the latter.

**Comment by lulco** [comment]
fixed in main, can you check please? I've moved composer manipulation out of the main nette-30 / nette-31 sets
